### ISSUE TITLE
Poliphony is not supported

### ISSUE THREAD

**Issue by nicola-lunghi** [mikromodular/libmidi#5]
Hi,
is my impression or if you receive a note on message the library wait for a note off?

Thanks,
Nick

**Comment by nicola-lunghi** [comment]
sorry my mistake :-)

**Comment by dialtr** [comment]
Nicola,

Thanks for your interest. I am curious, are you planning on using the
library? I have had very little time to work on hobbies lately and so it's
been some time since I looked at the library. However, your comments
inspired me to make more time for this!

Thanks
Tom
